name: csv output 

on:
  push:
    branches: [ master ]
jobs:

  curl:
    runs-on: windows-latest
    steps:
    - name: curl
      run: curl -X GET https://api.github.com/repos/nihar30/JestReport/commits >> "./output.json"

    - name: Upload a Test Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
      # Artifact name
        name: artifact
        path: ./output.json
